
services:
  node_app:
    build: .
    image: jcgarzon/nodejs_live_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=database-api
      - PG_USER=postgres
      - PG_PASSWORD=1234
      - PG_HOST=node_db
    restart: always
    depends_on:
      node_db:
        condition: service_healthy

  node_db:
    image: postgres:14.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=database-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - node_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database-api"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  node_db_data: {}
